version: '3.8'

services:
  ticketbot-postgres:
    image: postgres:15-alpine
    container_name: ticketbot-db
    restart: always
    environment:
      # Vamos definir apenas o utilizador e senha do super-admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
    driver: local